name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (format 1.2.3)
        required: true

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Create git tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ github.event.inputs.version }}",
              sha: context.sha
            })
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
